### ISSUE TITLE
Rename repo and files using hyphens instead of underscores

### ISSUE THREAD

**Issue by christophscheuch** [Teal-Insights/teal_insights_guide_to_wbids#1]
Since the output of this repo is a website with different subpages, I highly recommend using hyphens for files and the repo. The two most most compelling reasons why to use hyphens are:

1. Search engines like Google treat hyphens as word separators, making it easier for them to understand the words in the URL. 
2. Hyphens make URLs more readable for humans because URLs are often underlined, so underscores "disappear". 

I think it is better to make this breaking change as soon as possible before the docs are linked any further. 

I use underscores for all object and function names within a script and try to use hyphens for all files (incl. script files). Files that carry the name of a function are excluded from this rule (e.g. in package development).

**Comment by t-emery** [comment]
That's a great idea.  Better to make this change now.   I'll change when I have time (before I add more content)

**Comment by t-emery** [comment]
@Reu-hub can you go through, make another branch, change the repo name and file names from underscores to hyphens, as @christophscheuch suggests, and make sure that the book builds again properly?   Have @chriscarrollsmith help you make sure you're using best practices in creating the branch etc.

I've only sent the link to a few people, so I agree it's best to make these changes now.

Feel free to ping me if you have questions or if you need more admin rights.

**Comment by chriscarrollsmith** [comment]
@t-emery Reuben may or may not have permissions to actually edit the repository name; I know I don't. If not, you may have to do that part yourself.

**Comment by chriscarrollsmith** [comment]
@Reu-hub, I will make a short video about this and share it with you by end of day.

**Comment by chriscarrollsmith** [comment]
@Reu-hub here is the flow to complete this task. (I already completed steps 1-3 while I was writing up this documentation, so you can skip those!)

1. Find the "Development" section in the right sidebar of this issue
2. Click "Create a branch"
3. Select "Checkout locally" and click "Create branch"; go ahead and close the popup that comes up afterward
4. Open up RStudio
5. If you haven't already cloned this repository, click the "Terminal" tab in RStudio and clone the repository:
```shell
git clone https://github.com/Teal-Insights/teal_insights_guide_to_wbids.git
```
6. Open the .Rproj file for the project
7. Click the "Git" tab, click where it says "main" (your current branch) and switch to "1-rename-repo-and-files-using-hyphens-instead-of-underscores" (the issue branch)
8. Edit the file names, changing underscores to hyphens
9. In the "Git" tab, check all the boxes, click the "Commit" button and write a commit message, then click "Push" to push the changes to the remote branch
10. Come back here to GitHub, click the Pull Requests tab, and open a pull request from the issue branch to "main"
11. Assign someone to review the pull request

**Comment by t-emery** [comment]
> [@t-emery](https://github.com/t-emery) Reuben may or may not have permissions to actually edit the repository name; I know I don't. If not, you may have to do that part yourself.

@Reu-hub if you don't have permissions just let me know and I can change the repository name.

**Comment by t-emery** [comment]
I just went ahead and changed the repo name as it took 2 seconds.

**Comment by chriscarrollsmith** [comment]
@t-emery should review this pull request too, because it looks like you rendered and committed a bunch of HTML files that he may or may not want rendered/committed yet.

**Comment by t-emery** [comment]
> [@t-emery](https://github.com/t-emery) should review this pull request too, because it looks like you rendered and committed a bunch of HTML files that he may or may not want rendered/committed yet.

I'll re-render it when I get a chance.
